version: '2'
services:
    btcd:
      build:
        context: ./
        dockerfile: ./DockerfileLNDBTC
      ports:
          - "10001:10001"
          - "10002:10002"
          - "10003:10003"
      container_name: docker_lndbtc
